name: Document Version Tagger

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'
      - 'plans/**/*.md'

jobs:
  create-doc-tags:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to create tags
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit to compare
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Configure git
        run: |
          git config user.name "docs-bot"
          git config user.email "docs-bot@users.noreply.github.com"
      
      - name: Detect changed documents and create tags
        run: |
          python3 - << 'PYTHON_SCRIPT'
          import sys
          import subprocess
          from pathlib import Path
          import re
          
          def extract_metadata(file_path):
              """Extract doc_key and semver from front-matter"""
              try:
                  content = Path(file_path).read_text(encoding='utf-8')
              except Exception as e:
                  print(f"Warning: Cannot read {file_path}: {e}")
                  return None, None
              
              if not content.startswith('---'):
                  return None, None
              
              parts = content.split('---', 2)
              if len(parts) < 3:
                  return None, None
              
              doc_key = None
              semver = None
              
              for line in parts[1].strip().split('\n'):
                  if line.strip().startswith('doc_key:'):
                      doc_key = line.split(':', 1)[1].strip().strip('"').strip("'")
                  elif line.strip().startswith('semver:'):
                      semver = line.split(':', 1)[1].strip().strip('"').strip("'")
              
              return doc_key, semver
          
          def get_changed_files():
              """Get list of changed markdown files in last commit"""
              result = subprocess.run(
                  ['git', 'diff', '--name-only', 'HEAD~1', 'HEAD', '--', 'docs/**/*.md', 'plans/**/*.md'],
                  capture_output=True,
                  text=True,
                  check=True
              )
              
              files = [line.strip() for line in result.stdout.split('\n') if line.strip()]
              return files
          
          def tag_exists(tag_name):
              """Check if tag already exists"""
              result = subprocess.run(
                  ['git', 'tag', '-l', tag_name],
                  capture_output=True,
                  text=True
              )
              return bool(result.stdout.strip())
          
          def create_annotated_tag(tag_name, message, file_path):
              """Create annotated git tag"""
              try:
                  subprocess.run(
                      ['git', 'tag', '-a', tag_name, '-m', message],
                      check=True,
                      capture_output=True,
                      text=True
                  )
                  print(f"✓ Created tag: {tag_name}")
                  return True
              except subprocess.CalledProcessError as e:
                  print(f"❌ Failed to create tag {tag_name}: {e.stderr}")
                  return False
          
          def push_tags():
              """Push all tags to remote"""
              try:
                  subprocess.run(
                      ['git', 'push', '--tags'],
                      check=True,
                      capture_output=True,
                      text=True
                  )
                  print("✓ Pushed tags to remote")
                  return True
              except subprocess.CalledProcessError as e:
                  print(f"❌ Failed to push tags: {e.stderr}")
                  return False
          
          # Main logic
          print("Detecting changed documents...")
          changed_files = get_changed_files()
          
          if not changed_files:
              print("No documentation files changed in this commit")
              sys.exit(0)
          
          print(f"Found {len(changed_files)} changed file(s):")
          for f in changed_files:
              print(f"  • {f}")
          
          print("\nCreating version tags...")
          tags_created = []
          
          for file_path in changed_files:
              # Skip deleted files
              if not Path(file_path).exists():
                  print(f"⚠ Skipping deleted file: {file_path}")
                  continue
              
              # Extract metadata
              doc_key, semver = extract_metadata(file_path)
              
              if not doc_key or not semver:
                  print(f"⚠ Skipping {file_path}: No doc_key or semver found")
                  continue
              
              # Generate tag name
              tag_name = f"docs-{doc_key}-{semver}"
              
              # Check if tag already exists
              if tag_exists(tag_name):
                  print(f"⚠ Tag {tag_name} already exists, skipping")
                  continue
              
              # Create tag
              message = f"Document version: {doc_key} v{semver}\n\nFile: {file_path}"
              if create_annotated_tag(tag_name, message, file_path):
                  tags_created.append(tag_name)
          
          # Push tags
          if tags_created:
              print(f"\nPushing {len(tags_created)} new tag(s)...")
              if push_tags():
                  print("\n✅ Successfully created and pushed version tags:")
                  for tag in tags_created:
                      print(f"  • {tag}")
              else:
                  print("\n❌ Failed to push tags")
                  sys.exit(1)
          else:
              print("\nNo new tags to create")
          
          PYTHON_SCRIPT
      
      - name: Summary
        if: success()
        run: |
          echo "✅ Document versioning complete"
          echo ""
          echo "Each document version now has an immutable git tag:"
          echo "  • Format: docs-{doc_key}-{semver}"
          echo "  • Example: docs-OC_CORE-1.3.0"
          echo ""
          echo "You can checkout specific versions with:"
          echo "  git checkout docs-OC_CORE-1.3.0"
